[project]
name = "forest-rl-platform"
version = "0.1.0"
description = "Платформа для моделирования и обучения агентов в лесной среде"
requires-python = "==3.11.14"

dependencies = [
    "gymnasium>=1.2.3",
    "ipykernel>=7.2.0",
    "ipywidgets>=8.1.8",
    "jsonschema>=4.25.1",
    "keyboard>=0.13.5",
    "orjson>=3.11.8",
    "plotly>=6.7.0",
    "pydantic>=2.12.5",
    "rich>=14.3.3",
    "sb3-contrib>=2.8.0",
    "sqlalchemy>=2.0.49",
    "stable-baselines3>=2.7.1",
    "streamlit>=1.57.0",
    "tensorboard>=2.20.0",
    "uvicorn>=0.44.0",
    "websockets>=16.0",
    "torch==2.5.1+cu121",
    "fastapi>=0.136.3",
    "roslibpy>=2.0.0",
]

[tool.uv.sources]
torch = { index = "pytorch-cu121" }

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
