"""Initial

Revision ID: 6a7002181093
Revises: 
Create Date: 2026-03-11 17:06:06.901345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a7002181093'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('algorithms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('family', sa.Enum('tabular', 'dqn', 'actor_critic', 'classic_planner', 'patrol_heuristic', 'hybrid', name='algorithmfamily'), nullable=False),
    sa.Column('mode', sa.Enum('trail', 'robot', 'patrol', 'fast_grid', name='projectmode'), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('trail', 'robot', 'patrol', 'fast_grid', name='projectmode'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'code', name='uix_project_code')
    )
    op.create_table('scenario_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.BigInteger(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('terrain_config_json', sa.JSON(), nullable=True),
    sa.Column('obstacle_config_json', sa.JSON(), nullable=True),
    sa.Column('event_config_json', sa.JSON(), nullable=True),
    sa.Column('sensor_config_json', sa.JSON(), nullable=True),
    sa.Column('reward_config_json', sa.JSON(), nullable=True),
    sa.Column('world_file_uri', sa.Text(), nullable=True),
    sa.Column('preview_image_uri', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scenario_id', 'version_no', name='uix_scenario_version')
    )
    op.create_table('runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('scenario_version_id', sa.BigInteger(), nullable=False),
    sa.Column('algorithm_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('mode', sa.Enum('trail', 'robot', 'patrol', 'fast_grid', name='projectmode'), nullable=False),
    sa.Column('status', sa.Enum('created', 'queued', 'running', 'finished', 'failed', 'cancelled', name='runstatus'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_layers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scenario_version_id', sa.BigInteger(), nullable=False),
    sa.Column('layer_type', sa.String(length=100), nullable=False),
    sa.Column('file_uri', sa.Text(), nullable=False),
    sa.Column('file_format', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scenario_version_id'], ['scenario_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('episode_index', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('terminated_by', sa.String(length=100), nullable=True),
    sa.Column('reward_total', sa.Float(), nullable=True),
    sa.Column('steps_count', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('path_length', sa.Float(), nullable=True),
    sa.Column('path_cost', sa.Float(), nullable=True),
    sa.Column('collisions_count', sa.Integer(), nullable=True),
    sa.Column('coverage_ratio', sa.Float(), nullable=True),
    sa.Column('avg_detection_delay', sa.Float(), nullable=True),
    sa.Column('total_damage', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'episode_index', name='uix_run_episode')
    )
    op.create_table('metric_series',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('aggregation', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name', 'aggregation', name='uix_run_metric')
    )
    op.create_table('models',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=100), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('checkpoint_epoch', sa.Integer(), nullable=True),
    sa.Column('is_best', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'tag', name='uix_run_tag')
    )
    op.create_table('service_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=True),
    sa.Column('artifact_type', sa.Enum('world_file', 'scenario_preview', 'config', 'log', 'replay', 'model_checkpoint', 'metric_export', 'report', 'plot', 'map_layer', name='artifacttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('episode_id', sa.BigInteger(), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=True),
    sa.Column('sim_time_sec', sa.Float(), nullable=True),
    sa.Column('event_type', sa.Enum('collision', 'goal_reached', 'timeout', 'deadlock', 'fire_started', 'fire_detected', 'fire_missed', 'violator_started', 'violator_detected', 'violator_intercepted', 'patrol_zone_visited', name='eventtype'), nullable=False),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('z', sa.Float(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('metric_series_id', sa.BigInteger(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('train_step', sa.BigInteger(), nullable=True),
    sa.Column('episode_index', sa.Integer(), nullable=True),
    sa.Column('wall_time_sec', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_series_id'], ['metric_series.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric_series_id', 'point_index', name='uix_series_point')
    )
    op.create_table('replays',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('episode_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_uri', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replays')
    op.drop_table('metric_points')
    op.drop_table('episode_events')
    op.drop_table('artifacts')
    op.drop_table('service_logs')
    op.drop_table('run_tags')
    op.drop_table('models')
    op.drop_table('metric_series')
    op.drop_table('episodes')
    op.drop_table('scenario_layers')
    op.drop_table('runs')
    op.drop_table('scenario_versions')
    op.drop_table('scenarios')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('algorithms')
    # ### end Alembic commands ###
