//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Forest
{
    [Serializable]
    public class SetGoalRequest : Message
    {
        public const string k_RosMessageName = "forest_msgs/SetGoal";
        public override string RosMessageName => k_RosMessageName;

        public float position_x;
        public float position_y;
        public float position_z;
        public float radius;

        public SetGoalRequest()
        {
            this.position_x = 0.0f;
            this.position_y = 0.0f;
            this.position_z = 0.0f;
            this.radius = 0.0f;
        }

        public SetGoalRequest(float position_x, float position_y, float position_z, float radius)
        {
            this.position_x = position_x;
            this.position_y = position_y;
            this.position_z = position_z;
            this.radius = radius;
        }

        public static SetGoalRequest Deserialize(MessageDeserializer deserializer) => new SetGoalRequest(deserializer);

        private SetGoalRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position_x);
            deserializer.Read(out this.position_y);
            deserializer.Read(out this.position_z);
            deserializer.Read(out this.radius);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position_x);
            serializer.Write(this.position_y);
            serializer.Write(this.position_z);
            serializer.Write(this.radius);
        }

        public override string ToString()
        {
            return "SetGoalRequest: " +
            "\nposition_x: " + position_x.ToString() +
            "\nposition_y: " + position_y.ToString() +
            "\nposition_z: " + position_z.ToString() +
            "\nradius: " + radius.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
