//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Forest
{
    [Serializable]
    public class SetRobotsRequest : Message
    {
        public const string k_RosMessageName = "forest_msgs/SetRobots";
        public override string RosMessageName => k_RosMessageName;

        //  Request
        public float[] positions_x;
        public float[] positions_y;
        public float[] positions_z;
        public float[] rotations_y;
        public int[] type;

        public SetRobotsRequest()
        {
            this.positions_x = new float[0];
            this.positions_y = new float[0];
            this.positions_z = new float[0];
            this.rotations_y = new float[0];
            this.type = new int[0];
        }

        public SetRobotsRequest(float[] positions_x, float[] positions_y, float[] positions_z, float[] rotations_y, int[] type)
        {
            this.positions_x = positions_x;
            this.positions_y = positions_y;
            this.positions_z = positions_z;
            this.rotations_y = rotations_y;
            this.type = type;
        }

        public static SetRobotsRequest Deserialize(MessageDeserializer deserializer) => new SetRobotsRequest(deserializer);

        private SetRobotsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.positions_x, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.positions_y, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.positions_z, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.rotations_y, sizeof(float), deserializer.ReadLength());
            deserializer.Read(out this.type, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.positions_x);
            serializer.Write(this.positions_x);
            serializer.WriteLength(this.positions_y);
            serializer.Write(this.positions_y);
            serializer.WriteLength(this.positions_z);
            serializer.Write(this.positions_z);
            serializer.WriteLength(this.rotations_y);
            serializer.Write(this.rotations_y);
            serializer.WriteLength(this.type);
            serializer.Write(this.type);
        }

        public override string ToString()
        {
            return "SetRobotsRequest: " +
            "\npositions_x: " + System.String.Join(", ", positions_x.ToList()) +
            "\npositions_y: " + System.String.Join(", ", positions_y.ToList()) +
            "\npositions_z: " + System.String.Join(", ", positions_z.ToList()) +
            "\nrotations_y: " + System.String.Join(", ", rotations_y.ToList()) +
            "\ntype: " + System.String.Join(", ", type.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
