//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Forest
{
    [Serializable]
    public class SetRobotsResponse : Message
    {
        public const string k_RosMessageName = "forest_msgs/SetRobots";
        public override string RosMessageName => k_RosMessageName;

        //  Response
        public bool success;
        public string message;

        public SetRobotsResponse()
        {
            this.success = false;
            this.message = "";
        }

        public SetRobotsResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static SetRobotsResponse Deserialize(MessageDeserializer deserializer) => new SetRobotsResponse(deserializer);

        private SetRobotsResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "SetRobotsResponse: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
