//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Forest
{
    [Serializable]
    public class SetTerrainParamsRequest : Message
    {
        public const string k_RosMessageName = "forest_msgs/SetTerrainParams";
        public override string RosMessageName => k_RosMessageName;

        public float uniform_scale;
        public float mesh_height_multiplayer;
        public float noise_scale;
        public int seed;
        public int octaves;
        public float persistance;
        public float lacunarity;
        public float offset_x;
        public float offset_y;
        public int density;
        public int max_view_dst;
        public int noise_normalize_mode;

        public SetTerrainParamsRequest()
        {
            this.uniform_scale = 0.0f;
            this.mesh_height_multiplayer = 0.0f;
            this.noise_scale = 0.0f;
            this.seed = 0;
            this.octaves = 0;
            this.persistance = 0.0f;
            this.lacunarity = 0.0f;
            this.offset_x = 0.0f;
            this.offset_y = 0.0f;
            this.density = 0;
            this.max_view_dst = 0;
            this.noise_normalize_mode = 0;
        }

        public SetTerrainParamsRequest(float uniform_scale, float mesh_height_multiplayer, float noise_scale, int seed, int octaves, float persistance, float lacunarity, float offset_x, float offset_y, int density, int max_view_dst, int noise_normalize_mode)
        {
            this.uniform_scale = uniform_scale;
            this.mesh_height_multiplayer = mesh_height_multiplayer;
            this.noise_scale = noise_scale;
            this.seed = seed;
            this.octaves = octaves;
            this.persistance = persistance;
            this.lacunarity = lacunarity;
            this.offset_x = offset_x;
            this.offset_y = offset_y;
            this.density = density;
            this.max_view_dst = max_view_dst;
            this.noise_normalize_mode = noise_normalize_mode;
        }

        public static SetTerrainParamsRequest Deserialize(MessageDeserializer deserializer) => new SetTerrainParamsRequest(deserializer);

        private SetTerrainParamsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.uniform_scale);
            deserializer.Read(out this.mesh_height_multiplayer);
            deserializer.Read(out this.noise_scale);
            deserializer.Read(out this.seed);
            deserializer.Read(out this.octaves);
            deserializer.Read(out this.persistance);
            deserializer.Read(out this.lacunarity);
            deserializer.Read(out this.offset_x);
            deserializer.Read(out this.offset_y);
            deserializer.Read(out this.density);
            deserializer.Read(out this.max_view_dst);
            deserializer.Read(out this.noise_normalize_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.uniform_scale);
            serializer.Write(this.mesh_height_multiplayer);
            serializer.Write(this.noise_scale);
            serializer.Write(this.seed);
            serializer.Write(this.octaves);
            serializer.Write(this.persistance);
            serializer.Write(this.lacunarity);
            serializer.Write(this.offset_x);
            serializer.Write(this.offset_y);
            serializer.Write(this.density);
            serializer.Write(this.max_view_dst);
            serializer.Write(this.noise_normalize_mode);
        }

        public override string ToString()
        {
            return "SetTerrainParamsRequest: " +
            "\nuniform_scale: " + uniform_scale.ToString() +
            "\nmesh_height_multiplayer: " + mesh_height_multiplayer.ToString() +
            "\nnoise_scale: " + noise_scale.ToString() +
            "\nseed: " + seed.ToString() +
            "\noctaves: " + octaves.ToString() +
            "\npersistance: " + persistance.ToString() +
            "\nlacunarity: " + lacunarity.ToString() +
            "\noffset_x: " + offset_x.ToString() +
            "\noffset_y: " + offset_y.ToString() +
            "\ndensity: " + density.ToString() +
            "\nmax_view_dst: " + max_view_dst.ToString() +
            "\nnoise_normalize_mode: " + noise_normalize_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
