export const SLIDER_CONFIG = {
  "Непрерывная 2D": {
    "Тропы": {
      algos: {
        "PPO": { excludeParams: [] },
        "SAC": { excludeParams: ["ent_coef"] },
        "A2C": { excludeParams: ["ent_coef"] },
      },
      "Алгоритм": [
        { param: "max_steps", label: "Макс. шагов", default: 240, min: 50, max: 1000, step: 10 },
        { param: "goal_reward", label: "Награда за цель", default: 50, min: 10, max: 100, step: 5 },
        { param: "collision_penalty", label: "Штраф столкн.", default: 0.3, min: 0, max: 5, step: 0.1 },
      ],
      "Карта": [
        { param: "grid_size", label: "Размер сетки", default: 12, min: 5, max: 20, step: 1 },
        { param: "obstacle_density", label: "Препятствия", default: 0.12, min: 0, max: 0.4, step: 0.01 },
      ],
      "Робот": [
        { param: "action_scale", label: "Масштаб действий", default: 1.0, min: 0.1, max: 5, step: 0.1 },
        { param: "max_speed", label: "Макс. скорость", default: 50, min: 1, max: 200, step: 1 },
        { param: "accel", label: "Разгон", default: 40, min: 1, max: 100, step: 1 },
        { param: "damping", label: "Торможение", default: 0.6, min: 0.01, max: 0.99, step: 0.01 },
        { param: "dt", label: "Шаг физики", default: 0.01, min: 0.001, max: 0.05, step: 0.001 },
      ],
    },
    "Покрытие": {
      algos: {
        "greedy_nearest": { excludeParams: [] },
        "greedy_two_step": { excludeParams: [] },
        "PPO": { excludeParams: [] },
        "SAC": { excludeParams: ["ent_coef"] },
        "A2C": { excludeParams: ["ent_coef"] },
      },
      "Награды": [
        { param: "max_steps", label: "Макс. шагов", default: 240, min: 50, max: 1000, step: 10 },
      ],
    },
  },
  "Дискретная": {
    "Патруль": {
      algos: {
        "PPO": { excludeParams: [] },
        "A2C": { excludeParams: [] },
        "DQN": { excludeParams: [] },
        "DRQN": { excludeParams: [] },
      },
      "Генерировать сценарий": [
        { param: "grid_size", label: "Размер сетки", default: 16, min: 8, max: 32, step: 1, type: "int" },
        { param: "map_seed", label: "Seed карты (0=random)", default: null, min: 0, max: 99999999, step: 1, type: "number" },
        { param: "passability_low", label: "Мин. проходимость", default: 0.9, min: 0, max: 1, step: 0.05 },
        { param: "passability_high", label: "Макс. проходимость", default: 0.9, min: 0, max: 1, step: 0.05 },
        { param: "impassable_prob", label: "Непроходимость", default: 0.1, min: 0, max: 0.5, step: 0.01 },
        { param: "max_value", label: "Макс. ценность", default: 100, min: 10, max: 1000, step: 10, type: "int" },
        { param: "value_density", label: "Плотность ценности", default: 0.7, min: 0, max: 1, step: 0.05 },
        { param: "agent_is_random_spawned", label: "Случайный спавн агента", default: true, type: "bool" },
        { param: "spawn_min_passability", label: "Мин. проходимость спавна", default: 1.0, min: 0, max: 1, step: 0.1 },
        { param: "agent_pos_x", label: "Позиция агента X", default: 3, min: 0, max: 31, step: 1, type: "int" },
        { param: "agent_pos_y", label: "Позиция агента Y", default: 3, min: 0, max: 31, step: 1, type: "int" },
        { param: "intruder_count", label: "Кол-во нарушителей", default: 1, min: 1, max: 10, step: 1, type: "int" },
        { param: "intruder_is_random_spawned", label: "Случайный спавн нарушителя", default: false, type: "bool" },
        { param: "m_plan", label: "План ущерба", default: 175, min: 10, max: 1000, step: 5, type: "int" },
        { param: "m_tool_power", label: "Мощность инструмента", default: 2.0, min: 0.5, max: 100, step: 0.5 },
        { param: "m_defence", label: "Защита", default: 1.5, min: 0, max: 5, step: 0.1 },
        { param: "search_patience", label: "Терпение поиска", default: 50, min: 5, max: 200, step: 5, type: "int" },
        { param: "incoming", label: "Входящий нарушитель", default: true, type: "bool" },
        { param: "incoming_step", label: "Момент появления", default: -1, min: -1, max: 500, step: 1, type: "int" },
        { param: "incoming_patience", label: "Терпение входа", default: 15, min: 5, max: 200, step: 5, type: "int" },
        { param: "felling_intensity", label: "Интенсивность вырубки", default: 100, min: 0, max: 200, step: 1, type: "int" },
        { param: "m_catch", label: "Награда за поимку", default: 350, min: 0, max: 1000, step: 10, type: "int" },
        { param: "m_exit_penalty", label: "Штраф выход", default: -250, min: -1000, max: 0, step: 10, type: "int" },
        { param: "m_out", label: "Штраф выход", default: 1.0, min: 0, max: 10, step: 0.1 },
        { param: "m_stay", label: "Штраф стояния", default: 0.3, min: 0, max: 5, step: 0.1 },
        { param: "m_block", label: "Штраф блок", default: 0.5, min: 0, max: 10, step: 0.1 },
        { param: "exploration_reward", label: "Награда за исследование", default: 0.1, min: 0, max: 2, step: 0.05 },
        { param: "useful_exp_reward", label: "Награда за полезное исслед.", default: 0.3, min: 0, max: 2, step: 0.05 },
        { param: "max_steps", label: "Макс. шагов", default: 256, min: 50, max: 1000, step: 10, type: "int" },
        { param: "tau_min", label: "Мин. тау", default: 25, min: 1, max: 200, step: 5, type: "int" },
        { param: "tau_max", label: "Макс. тау", default: 75, min: 5, max: 500, step: 5, type: "int" },
      ],
    },
    "Посадка": {   // <-- ПЕРЕМЕСТИЛАСЬ ВНУТРЬ "Дискретная"
      algos: {
        "PPO": { excludeParams: [] },
        "A2C": { excludeParams: [] },
      },
      "Алгоритм": [
        { param: "max_steps", label: "Макс. шагов", default: 240, min: 50, max: 1000, step: 10 },
        { param: "step_penalty", label: "Штраф за шаг", default: 0, min: 0, max: 1, step: 0.01 },
        { param: "alpha_plant", label: "Награда за посадку", default: 4.0, min: 0.5, max: 10, step: 0.1 },
        { param: "alpha_quality", label: "Вес качества", default: 2.0, min: 0, max: 5, step: 0.1 },
        { param: "beta_move", label: "Штраф движения", default: 0.08, min: 0, max: 1, step: 0.01 },
        { param: "beta_turn", label: "Штраф поворота", default: 0.04, min: 0, max: 1, step: 0.01 },
        { param: "beta_invalid_plant", label: "Штраф плохой посадки", default: 0.6, min: 0, max: 2, step: 0.01 },
      ],
      "Карта": [
        { param: "grid_size", label: "Размер сетки", default: 12, min: 5, max: 20, step: 1 },
        { param: "obstacle_density", label: "Препятствия", default: 0.12, min: 0, max: 0.4, step: 0.01 },
        { param: "plantable_density", label: "Засаживаемость", default: 0.7, min: 0.1, max: 1, step: 0.01 },
        { param: "min_plant_distance", label: "Мин. расстояние", default: 1, min: 0, max: 3, step: 1 },
        { param: "uniformity_radius", label: "Радиус равномерн.", default: 1, min: 0, max: 3, step: 1 },
        { param: "target_density", label: "Целевая плотн.", default: 0.35, min: 0.05, max: 0.8, step: 0.01 },
        { param: "lambda_uniformity", label: "Штраф равномерн.", default: 3.0, min: 0, max: 10, step: 0.1 },
        { param: "lambda_underplanting", label: "Штраф недопосадки", default: 1.5, min: 0, max: 10, step: 0.1 },
      ],
      "Робот": [
        { param: "initial_seedlings", label: "Саженцев на борту", default: 30, min: 5, max: 80, step: 1 },
        { param: "beta_stay", label: "Штраф стояния", default: 0.12, min: 0, max: 1, step: 0.01 },
        { param: "beta_fail_move", label: "Штраф неудачи хода", default: 0.25, min: 0, max: 2, step: 0.01 },
      ],
    },
  },
  "3D симулятор": {
    "Тропы": {
      algos: {
        "PPO": { excludeParams: [] },
        "SAC": { excludeParams: [] },
        "A2C": { excludeParams: [] },
      },
      "Награды": [
        { param: "max_steps", label: "Макс. шагов", default: 240, min: 50, max: 1000, step: 10, type: "int" },
        { param: "goal_reward", label: "Награда за цель", default: 50, min: 10, max: 100, step: 5 },
        { param: "collision_penalty", label: "Штраф столкн.", default: 0.3, min: 0, max: 10, step: 0.5 },
        { param: "step_penalty", label: "Штраф за шаг", default: 0, min: 0, max: 2, step: 0.05 },
        { param: "terrain_penalty", label: "Штраф рельефа", default: 0.03, min: 0, max: 2, step: 0.05 },
      ],
      "Ландшафт": [
        { param: "mesh_height_multiplayer", label: "Множитель высоты", default: 1.0, min: 0.5, max: 5, step: 0.1, type: "number" },
        { param: "noise_scale", label: "Масштаб шума", default: 150.0, min: 0.001, max: 500.0, step: 0.1, type: "number" },
        { param: "seed", label: "Seed ландшафта", default: 42, min: 0, max: 999999, step: 1, type: "number" },
        { param: "octaves", label: "Детализация слоёв шума", default: 4, min: 1, max: 8, step: 1, type: "int" },
        { param: "lacunarity", label: "Частотный множитель слоёв", default: 2.0, min: 1.5, max: 3.5, step: 0.1 },
        { param: "density", label: "Плотность объектов", default: 10, min: 0, max: 100, step: 1, type: "int" },
        { param: "max_view_dst", label: "Размер ландшафта", default: 1, min: 1, max: 3, step: 1, type: "int" },
      ],
      "Робот": [
        { param: "robot_type", label: "Тип робота", type: "select", options: [0, 1], default: 0 },
        { param: "robot_position_x", label: "X", default: 0, type: "coordinates", group: "robot" },
        { param: "robot_position_y", label: "Y", default: 0, type: "coordinates", group: "robot" },
        { param: "robot_position_z", label: "Z", default: 0, type: "coordinates", group: "robot" },
        { param: "robot_rotation_y", label: "Поворот (Y)", default: 0, min: 0, max: 360, step: 15, type: "int" },
      ],
      "Цель": [
        { param: "target_position_x", label: "X", default: 0, type: "coordinates", group: "target" },
        { param: "target_position_y", label: "Y", default: 0, type: "coordinates", group: "target" },
        { param: "target_position_z", label: "Z", default: 0, type: "coordinates", group: "target" },
        { param: "radius", label: "Радиус цели", default: 1.0, min: 0.1, max: 1000.0, step: 0.1, type: "number" },
      ],
    },
    "Патруль": {
      algos: {
        "PPO": { excludeParams: [] },
        "SAC": { excludeParams: [] },
        "A2C": { excludeParams: [] },
      },
      "Награды": [
        { param: "max_steps", label: "Макс. шагов", default: 240, min: 50, max: 1000, step: 10, type: "int" },
      ],
      "Ландшафт": [
        { param: "mesh_height_multiplayer", label: "Множитель высоты", default: 1.0, min: 0.5, max: 5, step: 0.1, type: "number" },
        { param: "noise_scale", label: "Масштаб шума", default: 150.0, min: 0.001, max: 500.0, step: 0.1, type: "number" },
        { param: "seed", label: "Seed ландшафта", default: 42, min: 0, max: 999999, step: 1, type: "number" },
        { param: "octaves", label: "Детализация слоёв", default: 4, min: 1, max: 8, step: 1, type: "int" },
        { param: "lacunarity", label: "Множитель слоёв", default: 2.0, min: 1.5, max: 3.5, step: 0.1 },
        { param: "density", label: "Плотность объектов", default: 10, min: 0, max: 100, step: 1, type: "int" },
        { param: "max_view_dst", label: "Размер ландшафта", default: 1, min: 1, max: 3, step: 1, type: "int" },
      ],
    },
  },
}