//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Forest
{
    [Serializable]
    public class EventMsg : Message
    {
        public const string k_RosMessageName = "forest_msgs/Event";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public byte type;
        public byte robot_id;
        public float x;
        public float y;
        public float value;

        public EventMsg()
        {
            this.header = new Std.HeaderMsg();
            this.type = 0;
            this.robot_id = 0;
            this.x = 0.0f;
            this.y = 0.0f;
            this.value = 0.0f;
        }

        public EventMsg(Std.HeaderMsg header, byte type, byte robot_id, float x, float y, float value)
        {
            this.header = header;
            this.type = type;
            this.robot_id = robot_id;
            this.x = x;
            this.y = y;
            this.value = value;
        }

        public static EventMsg Deserialize(MessageDeserializer deserializer) => new EventMsg(deserializer);

        private EventMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.type);
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.type);
            serializer.Write(this.robot_id);
            serializer.Write(this.x);
            serializer.Write(this.y);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "EventMsg: " +
            "\nheader: " + header.ToString() +
            "\ntype: " + type.ToString() +
            "\nrobot_id: " + robot_id.ToString() +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
